# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: ['https://portal.pizza-soft.ru/index.php/en/about-reuse-inc','https://pizza-soft.ru/2020/04/30/about-reuse-inc/','https://solutionsmanagerit.github.io/ReUse/','https://solutionsmanagerit.github.io/ReUse_Inc/']
